### ISSUE TITLE
Choix framework UI

### ISSUE THREAD

**Issue by VicoF** [ludoboulanger/cyclee-app#2]
- [x] Se renseigner sur les différents framework disponible
- [x] Documenter dans cette issue

**Comment by AntoineLaberge** [comment]
**MUI** -> [MUI library](https://mui.com/components/autocomplete/)

Pros
- Énormément de components 
- Grande communauté
- Très customizable

Cons
- Pas pour les débutants
- Se rapproche beaucoup du style Android/Google, donc demande plus de travail pour créer notre propre style
---
**Semantic** -> [Semantic react](https://react.semantic-ui.com/elements/button/)

Pros
- Facile d'utilisation
- Développement rapide

Cons
- Moins responsive
- Plus petite communauté
- Jeune framework

**Comment by AntoineLaberge** [comment]
Framework que je suis sûr d'utiliser:
- [Styled component](https://styled-components.com/) : Intégrer CSS dans nos components
- [Emotion](https://emotion.sh/docs/introduction) : Style nos components avec du CSS
- [Ionic](https://ionicframework.com/) : Cross-platform development. On peut utiliser Ionic pour le routing afin que l'app soit compatible avec mobile
- [React router v6](https://reactrouter.com/docs/en/v6/getting-started/overview) : Si on utilise pas Ionic

**Comment by VicoF** [comment]
Avec ce que t'as ressorti je crois qu'on est mieux d'y aller avec MUI! Ludo et moi on est habitué et c'est pas trop difficile de se distancier du style Google une fois qu'on sait ce qu'on veut faire je dirais.

Pour la lib styled component je vois pas trop l'intérêt par rapport à ce qui est fournis dans MUI directement. 
Pour Ionic j'ai cherché un peu et ça a l'air un peu complexe à intégrer avec next.js comme next je gère le routing aussi. Va falloir qu'on fasse des choix j'pense

**Comment by AntoineLaberge** [comment]
Je pense que MUI est le way to go! 

Pour la librairie Styled, ça permet de rendre les div ou n'importe quel tag HTML sous forme de composante REACT. À voir si besoin.

Pour le routing, la stack Next/Ionic est documenté ici : [Stack NEXT/Ionic](https://capacitorjs.com/blog/mobile-apps-with-tailwind-css-nextjs-ionic-and-capacitor)

**Comment by ludoboulanger** [comment]
@AntoineLaberge pourquoi `StyledComponent` MUI ne fait pas deja la job? On peut déja créer les styles directe en JS avec MUI

**Comment by AntoineLaberge** [comment]
@VicoF @ludoboulanger  J'avais pas remarquer avant ce matin que MUI offre une option semblable. Dans ma tête, la librairie `Styled` était l'option la plus simple.

**Comment by VicoF** [comment]
We will implement routing using only next.js and put Ionic in the ice for now. We will focus on web development and reconsider Ionic once we want an app.

**Comment by VicoF** [comment]
Choices have been officialized in #18
